language node_js
node_js:
  - "4.2"
  - "6.6.0"
before_install:
  - npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run travis
